### ISSUE TITLE
Video Comression not working

### ISSUE THREAD

**Issue by akashqss** [lalongooo/VideoCompressor#1] opened 2015-08-06 12:56 UTC
I am using your code .when click on compress button it forcefully closed. 

 Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.lalongooo.videocompressor.video.MediaController.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I

**Comment by lalongooo** [comment] 2015-08-06 15:17
What's the output of this command:

![image](https://cloud.githubusercontent.com/assets/1671260/9115354/4446ffec-3c24-11e5-8144-4fca1bb8df0c.png)

**Comment by akashqss** [comment] 2015-08-07 09:14
I am not getting any output in logcat when rebuild your project and when try to compress got above error.

**Comment by lalongooo** [comment] 2015-08-11 19:23
Please, apste here your Gradle Console outoput:

![image](https://cloud.githubusercontent.com/assets/1671260/9207659/78d243de-4034-11e5-8a2f-93e5b3c130ab.png)

**Comment by akashqss** [comment] 2015-08-12 05:57
Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
WARNING [Project: :app] Current NDK support is deprecated.  Alternative will be provided in the future.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportSupportV42220Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:preDexDebug UP-TO-DATE
:app:dexDebug
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 30.751 secs


its my Gradle Console Output

**Comment by lalongooo** [comment] 2015-08-14 20:52
I've spent last day trying to find what's wrong with the project without any success.. :cry: 

I cloned the repo from a clean Android Studio installation and all worked fine.

I'll ask [Babul Patel](http://stackoverflow.com/questions/31796711/fast-video-compression-like-whatsapp/31823187#31823187) for any issues he could have.

**Comment by lalongooo** [comment] 2015-08-17 04:44
@akashqss, everything seems to be ok as per the response from Babul. I will close this issue, please re-open if you think I can help you.

http://stackoverflow.com/questions/31796711/fast-video-compression-like-whatsapp/31823187?noredirect=1#comment51985448_31823187

**Closed by lalongooo** 2015-08-17 04:44 UTC

**Comment by kalyani30** [comment] 2016-04-28 10:22
getting this exception on clicking on compress video button....
This is happening only  <=sdk version 4.2 devices....

Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.lalongooo.videocompressor.video.MediaController.convertVideoFrame:(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIIII)I

please help me in this...

**Comment by kalyani30** [comment] 2016-04-29 13:03
After compression some of the video's size got increasing...

I have compressed .mp4 file with size 66mb after compression size got increased to 83.1mb..
why it will happen??

**Comment by lalongooo** [comment] 2016-04-29 16:51
Hi @kalyani30 , please take a look to this comment https://github.com/lalongooo/VideoCompressor/issues/2#issuecomment-155831075
